#!/bin/sh

project_dir="$1"
repl_cmd="lein repl"

# Take basename of PWD after changing to project dir in case it's given to us as
# '.' or '..' or similar.
cd "$1"
session="$(basename $PWD)"

tmux new-session -d -s "$session"

# Rather than starting each pane with a command we run the commands in each pane so that if we have to end or
# restart a command, we don't lose the pane
tmux rename-window "vim"
tmux send-keys -t "$session":vim.0 "vim" Enter
tmux send-keys -t "$session":vim.0 ":NERDTree" Enter

# Create a second window for shell and repl
tmux new-window -n shells
tmux split-window -h
tmux send-keys -t "$session":shells.1 "$repl_cmd" Enter

# Start at our vim window
tmux select-window -t "$session":vim
tmux -2 attach-session -t "$session"
